### ISSUE TITLE
Questions about gene expression dimensions

### ISSUE THREAD

**Issue by sugyun** [nomoresomethingwentwrong/GLDM_PyPi#2]
Thank you for doing such a wonderful job!

I have some questions.
The number of L1000 landmark genes is 978, as far as I know.
Why did you make a size 979 long dummy_gene_express?
what are the names of the 979 genes?

**Comment by conghaowang** [comment]
Hello Sugyun, 

Thanks for raising the issue. I forgot to explain for this in the instructions.
Besides the 978 gene expression value, the dummy_gene_expr also contains 1 dosage value of the treatment (appended at last). 
Will update the instructions later :)

Cheers,
Conghao

**Comment by sugyun** [comment]
Hello Conghao,

Thank you for your clear answer, it has been resolved thanks to you.
Have a great day.

Best regards,
Sugyun
